### PR TITLE
Don't transform html attributes with markdown rules

### PR DESCRIPTION
**Pull request by dpsutton**
`<a href=underscores_are_fine.com>link text</a>` should not have the
underscores replaced with <i> tags. link text should have this
transformation however.

solves [issue #133](https://github.com/yogthos/markdown-clj/issues/133)

### CODE REVIEW

**Comment by dpsutton** [comment]
this just goes on open `<` in general. So if someone wanted the text 

> The tag `<` prevents _emphasis_ for the rest of the line.

to have emphasis this would prevent that.

**Comment by dpsutton** [comment]
We are limited since we only have one line at a time and cannot do a full parser for xml but perhaps suppressing the italics if some heuristic for in xml element is true. Perhaps if the number of `<` and `>` is the same we assume we have wellformed xml and then do this?

Interestingly, the current version handles code blocks just fine so perhaps this is less of an issue in real life.

```clojure
;; `<` in code block
(md-to-html-string "If you see `<` in your text you _should run_ as fast as possible")
;;=> 
"<p>If you see <code>&lt;</code> in your text you <i>should run</i> as fast as possible</p>"
;; translates italics

;; just as string
(md-to-html-string "If you see < in your text you _should run_ as fast as possible")
;; =>
"<p>If you see < in your text you _should run_ as fast as possible</p>"
;; does not translate italics as it thinks it is in an xml tag

;; but we can't always know we are in an href due to single line context
(md-to-html-string "<a 
href='url_with_space'>link text </a>")
;; =>
"<p><a  href='url<i>with</i>space'>link text </a></p>"
```

**Comment by yogthos** [comment]
Thanks for the PR, it looks reasonable to me. I can't really think of a better approach than using a heuristic here either. Code blocks are simpler to parse since you know exactly when they start and end, so it's possible to disable the filters on them.

**Comment by yogthos** [comment]
and just released `1.0.8` to Clojars

**Comment by dpsutton** [comment]
thanks so much @yogthos !

**Comment by yogthos** [comment]
Thanks for the PR :)

**Pull request merged**
