### PR TITLE
Fixes buggy dropping of the front of a line in link processing

### PR DESCRIPTION
**Pull request by caryfitzhugh**

### CODE REVIEW

**Comment by caryfitzhugh** [comment]
Another change! I believe my refactoring of the link code introduces a bug which, when you had two or more links in a line, it would simply discard the previous iteration's "out".

**Comment by yogthos** [comment]
ah thanks

**Comment by yogthos** [comment]
I pushed out a release, hopefully everything should be in good shape now. :)

**Comment by caryfitzhugh** [comment]
ok great! I'll check it out tomorrow.

**Pull request merged**
