### PR TITLE
Update so that terminal chars dont collide

### PR DESCRIPTION
**Pull request by caryfitzhugh**

### CODE REVIEW

**Comment by yogthos** [comment]
I wonder if it might be better to generate a uuid for each tag?

**Comment by caryfitzhugh** [comment]
ooh. and then set it in the state?...  Interesting.

**Comment by caryfitzhugh** [comment]
I'll see what I can do.

**Comment by caryfitzhugh** [comment]
So - here is my first attempt.  A few notes

It does not try to escape things anymore - if you tell the system to "freeze" an output string, it just writes that into the state, and then emits a token in to the text.  I thought that regexes are expensive, so this may be faster / cheaper.  And it simplifies some things (I hope) since the # ~ * and ^ don't need to be explicitly called out for regexes.  

It replaces things with something like 
```
|!n!|  
```

And then at the end recursively looks for those things and expands them.

I feel a bit uneasy about the loop in there to unexpand things, but then again, I'm sure there are diabolical edge cases with normal markdown processors. So - maybe it's not a big deal to worry about in "real life".

n is the number of the tokenization.  So it starts at 1, then increases from there for every string you freeze. I was going to do a UUID or something (even hash the string) - but then cross-platformness bit me and I decided to just use the number. Which incidentally I am pretty sure is a lot faster to generate and locate in the text.

So that's the idea. I ran the tests, and everything passed. I was forced to fiddle some inner code so that the state is always passed around (so I can add a frozen-strings key to it).

**Comment by yogthos** [comment]
That seems like it should work, I can't think of a simple fix that wouldn't involve some sort of special characters hardcoded and it seems like this would be safe enough. I'll try it out and if nothing breaks I'll push it out then.

**Comment by yogthos** [comment]
I ended up doing a bit of a clean up, using `recur` makes sure the function doesn't eat the stack. I also realized that since the replacement text is only used internally I might as well use an extended ascii char as the delimiter so now it's `(char 254) n (char 254)` for the delimiter and that's pretty unlikely to collide with anything.

**Comment by caryfitzhugh** [comment]
Ah, ok, great. Sounds good.

**Comment by yogthos** [comment]
Also just pushed out `0.9.73` with a fix so that the parser only tries to thaw strings if frozen ones were created in a line, so the overhead should now only occur for the specific lines that have urls with escaped characters.

**Comment by caryfitzhugh** [comment]
Sweet. thanks again.

**Pull request merged**
