### PR TITLE
Test to exhibit bug in link HTML encoding.

### PR DESCRIPTION
**Pull request by dankreek**
My last attempt at this failed, so for now I'm just going to put this up as a demonstration of the bug I found. Don't really have time to dig into fixing today but wanted to put this up incase anyone else possibly had a moment and was more familiar with this code than I am.

### CODE REVIEW

**Comment by yogthos** [comment]
sounds good, I might have time to take a look at this in the near future ;)

**Comment by dankreek** [comment]
You mentioned in this repo's `README.md` that a user can use a custom transformer to escape HTML characters, but from what I can tell, all other markdown-to-HTML transformers do this by default. Should this be the normal behavior of this library?

**Comment by yogthos** [comment]
I don't really see too much of a downside to that, would probably just want to document that it's a breaking behavior.

**Comment by yogthos** [comment]
should be fixed in the new version, added tests as well

**Pull request closed without merging**
