### PR TITLE
Added support for image references (issue #74)

### PR DESCRIPTION
**Pull request by yurizhykin**
Added transformer for image url references:
``` markdown
![alt text][id]
...
[id]: http://example.com "Description text"
```

### CODE REVIEW

**Comment by yogthos** [comment]
looks great thanks!

**Comment by yogthos** [comment]
just pushed out a new version with the fix

**Comment by yurizhykin** [comment]
Great. BTW, thanks for a lib. I currently use it for a personal project, so will report issues if find some.

**Comment by yogthos** [comment]
thanks, and sounds good :)

**Pull request merged**
