### PR TITLE
Add class to footnotes list

### PR DESCRIPTION
**Pull request by landakram**
Hi @yogthos! This is a really tiny tweak that adds `.footnotes` as a class to the footnotes list. 

Without this class, I couldn't find an easy way to style the footnotes `ol` with pure css. 

Let me know if you need anything else!

### CODE REVIEW

**Comment by yogthos** [comment]
that seems reasonable :)

**Comment by yogthos** [comment]
just push a new version to clojars with the fix

**Comment by landakram** [comment]
Awesome! And thanks for the very useful library :)

**Comment by yogthos** [comment]
glad it's useful :)

**Pull request merged**
