### PR TITLE
Tables with less spaces

### PR DESCRIPTION
**Pull request by rutchkiwi**
Like these ones:

```
| apa | banan |
|-----|-------|
| 1   | 2     |
```

Before this change, only this syntax was allowed:

```
| apa | banan |
| --- | ----- |
| 1   | 2     |
```

which is a bit of a bummer since awesome tools like
https://stevecat.net/table-magic/ gives me the no-spaces syntax.

At my job the content team is responsible for creating these
sort of markdown tables for product ingredients, and they ALWAYS mess it
up so I thought they'd appricate some automated tools and a more leinient parser.

Oh, and thanks for this awesome library :)

### CODE REVIEW

**Comment by yogthos** [comment]
Totally makes sense, thanks for the fix!

**Comment by yogthos** [comment]
and up on Clojars

**Comment by rutchkiwi** [comment]
Thanks a lot! :)

**Comment by rutchkiwi** [comment]
Hey I upgraded the clojars version just fine now, but how do I get the JS version? I seem to remember grabbing the JS file from the demo page but that does not seem to be updated?

**Comment by yogthos** [comment]
Oh right, I have to push out a new version to NPM separately. Let me take a look here. :)

**Comment by yogthos** [comment]
ok latest should be up on npm

**Pull request merged**
