### PR TITLE
Add yaml and edn metadata processing; solves #153

### PR DESCRIPTION
**Pull request by metasoarous**
Complete with passing tests (solves #153).

Thanks for reviewing!

### CODE REVIEW

**Comment by yogthos** [comment]
Thanks that looks great. Might be worth adding a note about different formats in the readme as well.

**Comment by yogthos** [comment]
Unfortunately, it looks like `io.forward/yaml` is clj only. We'll need a solution that works for cljc or yaml parsing could be restricted to clj mode.

**Comment by yogthos** [comment]
I ended up throwing [unsupported error](https://github.com/yogthos/markdown-clj/blob/535ca9e7c72a9ce82fc60f2aeca4d33db8f87d36/src/cljc/markdown/transformers.cljc#L346) for cljs version, and `1.10.0` is up on Clojars with the new features.

**Comment by metasoarous** [comment]
Oh, bummer. I didn't realize that. Next time I'll make sure to run the cljs tests. In any case, thanks for the clj fix, and the release!

**Comment by yogthos** [comment]
No worries, and thanks for the PR. :)

**Pull request merged**
